
# Tcl/Expect code for the writeval test.
#
# $Id: unix.exp 12056 2005-09-01 19:10:10Z jimg $

# Compare $expected to the global $comp_output. Run `pass' if they match,
# `fail' otherwise unless `xfailp' is true in which case run `xfail' if they
# do not match. $msg is the name of the test to print when calling pass, fail
# or xfail.
#
# NB: $expected may be either a string or a file name. If it is the latter,
# read the file and compare its contents to $comp_output.

# Read the common code for tests.

if {[file exists common_tests.exp]} {
    source common_tests.exp
} else {
    send_user "Could not load common tests!"
    exit(1)
}

# The four `required' procs are _start, _load, _exit and _version.
# set 'is_data' to 'data' when testing data results (although any value
# other than 'no' will work).

proc fonc_start { {script ""} {outfile ""} } {
    global verbose
    global comp_output
    global spawn_id

    if {$verbose >= 1} {
        send_user "Testing file out netcdf $script"
    }

    exec ./$script
    catch "exec ncdump $outfile" comp_output
}

proc fonc_load {} {
}

proc fonc_exit {} {
    send -raw ""
}

proc fonc_version {} {
    send_user "file out netcdf test suite 0.9.0\n"
}

