# Test the file out netcdf transformation
#
# $Id: fonc.struct.01.exp 14588 2006-09-15 21:13:55Z pwest $

global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `0' in compare_stdout means call fail if the test fails.
# The `1' in compare_stdout means call xfail if the test fails.

fonc_start "structT01" "structT01.nc"
compare_stdout "baselines/fonc.struct.01.baseline" "File Out Nested Structures" 0

