# Test the file out netcdf transformation
#
# $Id: fonc.array.00.exp 14588 2006-09-15 21:13:55Z pwest $

global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `0' in compare_stdout means call fail if the test fails.
# The `1' in compare_stdout means call xfail if the test fails.

fonc_start "arrayT" "arrayT.nc"
compare_stdout "baselines/fonc.array.00.baseline" "File Out Array" 0

